defaults:
  - /airdialogue@synth_data: synthetic_sampler
  - /airdialogue@real_data: real_data
name: real_synth_table_dataset2
cond_reward_key: conditioned_reward
max_retries: 500
original_prob: 0.05
verbose: true
