defaults:
  - /discrete_features: agent_discrete_features
name: table_gpt2_LM
gpt2_type: "gpt2"
max_length: null
checkpoint_path: null
attn_prior: geometric
geometric_rate: 0.9
cond_reward_key: conditioned_reward
strict_load: true