defaults:
  - gpt2_LM@model: simplified_aux_gpt2_LM
  - torch_dataset@train_dataset: toy_synth_table_dataset2
  - torch_dataset@dev_dataset: toy_synth_table_dataset2
  - evaluator: toy_simplified_gpt2_evaluator
  - _self_

model:
  checkpoint_path: null

evaluator:
  max_turns: 4
  generation_kwargs:
    max_generation_len: 32

train:
  save_checkpoint_dir: outputs/GPT2_simplified_aux_test/
  optim_state_path: null
  epochs: 1
  dataloader_workers: 0
  bsize: 8
  grad_accum_steps: 8
  log_every: 256
  eval_every: 4096
  save_every: 16384
  eval_bsize: 8
  eval_batches: 16
  lr: 1e-4
  weight_decay: 0.01
  max_steps: null
  loss:
    aux_head_weight: 1.0

wandb:
  use_wandb: true
  wandb_project: gpt2_simplified_aux
  log_name: null

