defaults:
- bot@customer_bot: gpt2_customer_bot
- bot@agent_bot: full_gpt2_table_agent_bot
- torch_dataset@dataset: basic_dataset
- _self_

agent_bot:
 policy:
   kind: sample
   lm:
     checkpoint_path: outputs/instruct_agent_test/model.pkl
     # checkpoint_path: outputs/basic_agent2/model.pkl
 generation_kwargs:
   n: 1

customer_bot:
 policy:
   kind: sample
   lm:
     checkpoint_path: outputs/customer_bot2/model.pkl
 generation_kwargs:
   n: 1

dataset:
 data:
   filepath: data/processed_ad/dev_unfiltered_subset.json
   heauristic_filter: false
   filter_with_goal: false

selfplay:
 load_outputs_file: null
 outputs_file: outputs/selfplay_outputs/selfplay_test1.json
 max_turns: 40
 verbose: true
