defaults:
  - gpt2_LM@model: agent_gpt2_LM
  - torch_dataset@train_dataset: basic_dataset
  - torch_dataset@dev_dataset: basic_dataset
  - evaluator: agent_gpt2_evaluator
  - _self_

train_dataset:
  data:
    filepath: data/processed_ad/instruction_filtered_small.json
    heauristic_filter: false
    filter_with_goal: false

dev_dataset:
  data:
    filepath: data/processed_ad/instruction_filtered_small.json
    heauristic_filter: false
    filter_with_goal: false

model:
  checkpoint_path: null

evaluator:
  max_generation_len: 512

train:
  save_checkpoint_dir: outputs/basic_basic_agent/
  optim_state_path: null
  epochs: 100
  dataloader_workers: 0
  bsize: 2
  grad_accum_steps: 4
  log_every: 256
  eval_every: 4096
  save_every: 16384
  eval_bsize: 2
  eval_batches: 4
  lr: 1e-4
  weight_decay: 0.01
  max_steps: null
  loss: {}

wandb:
  use_wandb: true
  wandb_project: gpt2_basic_agent_train
  log_name: null

