defaults:
  - /bot@opposing_bot: toy_customer_bot
name: table_gpt2_evaluator
max_turns: 80
verbose: true
kind: sample
generation_kwargs:
  max_generation_len: null
  n: 1
  temp: 1.0
  top_k: null
  top_p: null